name: "⚡am"
picture: "assets/img/picture.jpg"
bio: "Explorer of fun stuff."
meta:
  lang: "en"
  description: "Explorer of fun stuff."
  title: "Sam's Nest"
  author: "Sam"
  siteUrl: "https://sam.com.in/"
links:
  - name: "WatchedList 2024"
    url: "https://sam-trg.notion.site/Movies-TV-List-2024-bd6dc70e941d4088bbbd172d5893a176"
  - name: "Sam Scans"
    url: "https://www.imdb.com/user/ur151289834/ratings/?ref_=ext_shr_lnk"
  - name: "Sam's Jams"
    url: "https://open.spotify.com/playlist/2bdbb8QYvwzvsOeSiuxHv1?si=y3ws82YSQ2uhOj_Ft6FuOQ"
  - name: "Sam Spams?"
    url: "https://sam.com.in/blog"
  - name: "Sam's Cam"
    url: "https://samarth.pp.ua/"
  - name: "Blast From The Past"
    url: "https://youtu.be/92YISZb8lIk?si=_5NSiwwTO1ztdm2l"
theme: "custom"
